sudo: false
language: python
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export AWS_DEFAULT_REGION=ap-northeast-1
  - chmod +x coverage.sh
script: 
  - ./coverage.sh
after_success:
  - coveralls
